---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: tap-aws-rds-1
spec:
  forProvider:
    description: Security Group for tap-aws-rds VPC
    name: tap-aws-rds-1
    region: eu-west-2
    vpcIdRef:
      name: tap-aws-rds
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: permit-psql-from-anywhere
spec:
  deletionPolicy: Delete
  forProvider:
    cidrBlocks:
    - 0.0.0.0/0
    fromPort: 5432
    protocol: tcp
    region: eu-west-2
    securityGroupIdRef:
      name: tap-aws-rds-1
    toPort: 5432
    type: ingress
