---
apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: tap-aws-rds-1
spec:
  forProvider:
    allocatedStorage: 20
    autoGeneratePassword: true
    passwordSecretRef:
      key: password
      name: tap-aws-rds-1
      namespace: crossplane-system
    region: eu-west-2
    instanceClass: db.t3.micro
    engine: postgres
    engineVersion: "13.7"
    name: tapawsrds1
    username: adminuser
    publiclyAccessible: true
    skipFinalSnapshot: true
  writeConnectionSecretToRef:
    name: tap-aws-rds-1-con-secret
    namespace: crossplane-system
