---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: tap-aws-rds-public-1
spec:
  forProvider:
    region: eu-west-2
    availabilityZone: eu-west-2a
    vpcIdRef:
      name: tap-aws-rds
    cidrBlock: 10.0.0.0/17
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: tap-aws-rds-public-2
spec:
  forProvider:
    region: eu-west-2
    availabilityZone: eu-west-2b
    vpcIdRef:
      name: tap-aws-rds
    cidrBlock: 10.0.128.0/17
